package com.mustafayusef.holidaymaster.Models.ticketDetails

data class Data(
    val AdultBaseFare: Double,
    val AdultTax: Double,
    val AirlineCode: String,
    val AirlineName: String,
    val ChildBaseFare: Double,
    val ChildTax: Double,
    val Class: String,
    val Duration: List<String>,
    val FlightNo: List<String>,
    val InfantBaseFare: Double,
    val InfantTax: Double,
    val Refundable: String,
    val _id: String,
    val airCraftType: List<String>,
    val airNames: List<String>,
    val arrAirportName: List<String>,
    val arrCityName: List<String>,
    val arrDateAndTime: List<String>,
    val depAirportName: List<String>,
    val depCityName: List<String>,
    val depDateAndTime: List<String>,
    val layoverTime: List<String>,
    val logos: List<String>,
    val mainLogo: String,
    val price: Double,
    val stops: Int,
    val totalDuration: String
)